# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WnXFMwKT0ZfzZdTLbrlF29jQ44nLEhTI
"""

import streamlit as st
import tensorflow as tf
from tensorflow.keras.preprocessing import image
import numpy as np
import os

# Load the trained model (make sure it's in the same directory or provide the correct path)
model = tf.keras.models.load_model('trained_model.h5')

# Streamlit interface
st.title('Food Item Classifier -by Astha')

# Upload Image
uploaded_image = st.file_uploader("Choose any image...", type="jpg")

if uploaded_image is not None:
    # Show image to user
    st.image(uploaded_image, caption='Uploaded Image', use_column_width=True)
    st.write("")

    # Preprocess the image
    img = image.load_img(uploaded_image, target_size=(150, 150))
    img_array = image.img_to_array(img)
    img_array = np.expand_dims(img_array, axis=0)  # Add batch dimension
    img_array = img_array / 255.0  # Normalize the image

    # Make prediction
    predictions = model.predict(img_array)
    predicted_class = np.argmax(predictions, axis=-1)

    # Display prediction
    st.write(f"Predicted Class: {predicted_class}")
    # Optionally, display confidence score or class name
    st.write(f"Prediction Confidence: {np.max(predictions)}")